# Generated by Django 4.1.7 on 2023-03-09 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('emp_name', models.CharField(max_length=10, null=True, unique=True, verbose_name='직원 이름')),
                ('age', models.IntegerField(null=True, verbose_name='나이')),
                ('ent_date', models.DateField(verbose_name='입사일')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=1, null=True, verbose_name='성별')),
                ('position', models.CharField(max_length=10, null=True, verbose_name='직군')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='주소')),
                ('rised_num', models.CharField(max_length=14, null=True, verbose_name='주민반호')),
                ('zip_cde', models.CharField(max_length=7, null=True, verbose_name='우편 번호')),
                ('retire_date', models.DateField(null=True, verbose_name='퇴사일')),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
