# Generated by Django 4.1.7 on 2023-03-09 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='retire_date',
            field=models.DateField(blank=True, null=True, verbose_name='퇴사일'),
        ),
    ]
